version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:7-jammy

    container_name: customer-mongodb-container

    ports:
      - "27007:27017"
    
    volumes:
      - ./mongodb:/data/db
    
    networks:
      - backend
    
    restart: always
    
    #command: ["mongod", "--replSet", "rs0"]

  
  qdrant:
    image: qdrant/qdrant

    container_name: customer-qdrant-container

    ports:
      - "6334:6333"
    
    volumes:
      - ./qdrant:/data/db
    
    networks:
      - backend
      
    restart: always

    


networks:
  backend: